/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC5
 * Generated at: 2013-12-13 05:53:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import raspiejukebox.*;
import java.util.List;
import java.net.URLEncoder;

public final class trackselect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html\n");
      out.write("\tPUBLIC \"-//W3D//DTD XHTML 1.0 Strict//EN\"\n");
      out.write("\t\t\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"basicstyle.css\" />\n");
      out.write("<script src=\"xmlfunctions.js\" type=\"text/javascript\"></script>\n");
      out.write("</head>\n");
      out.write("\n");

TracksDatabase tdb = TracksDatabase.get();

String songToAdd = request.getParameter("addsong");
if (songToAdd != null)
	JukeBox.get().addToQueue(tdb.getTrackByID(Integer.parseInt(songToAdd)));

String artistName = (String)request.getParameter("artistname");

if (artistName == null) { 
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div style=\"padding-top:0.5em; padding-bottom:0.5em; font-size:1.75em; padding-left:0.5em;\">Artists</div>\n");
      out.write("\t<table cellspacing=\"0\" style=\"width:100%\">\n");
      out.write("\t\t");

		int i = 0;
		String rowFormat = "<tr class=\"d%d selectable\" onClick=\"document.location='trackselect.jsp?artistname=%s'\"><td style=\"border-right:none\">%s</td></tr>";


		for (String artist: tdb.getArtists())
			out.print(String.format(rowFormat, ++i%2, URLEncoder.encode(artist, "UTF-8"), artist));
		
      out.write("\n");
      out.write("\t</table>\n");
      out.write("</body>\n");
      out.write("\n");
} else {
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div style=\"padding-top: 0.5em; padding-bottom: 0.5em\">\n");
      out.write("\t\t<span style=\"font-size:1.75em; padding-left:0.5em;\">");
      out.print(artistName);
      out.write("</span>\n");
      out.write("\t\t<span class=\"selectable\" style=\"padding-left:3em;\" onClick=\"history.back();\">Back</span>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<table cellspacing=\"0\" style=\"width:100%;table-layout:fixed\">\n");
      out.write("\t\t<colgroup>\n");
      out.write("\t\t\t<col style=\"width:2em;\" />\n");
      out.write("\t\t\t<col style=\"width:80%;\" />\n");
      out.write("\t\t\t<col style=\"width:20%;\" />\n");
      out.write("\t\t</colgroup>\n");
      out.write("\t\t<tr class=\"d0\"><th>#</th><th>Name</th><th>Album</th></tr>\n");
      out.write("\t\t");

		List<TracksDatabase.Track> tracksForArtist = null;
		tracksForArtist = tdb.getTracksByArtist(artistName);
		int i = 0;
		
		String sFormat = "<tr class=\"d%d selectable\" onClick=\"addSong(%d);\"><td>%d</td><td>%s</td><td style=\"border-right:none;\">%s</td></tr>";
		for (TracksDatabase.Track track: tracksForArtist)
			out.println(String.format(sFormat, ++i%2, track.getID(), track.getTrackNumber(), track.getName(), track.getAlbum()));
		
      out.write("\n");
      out.write("\t</table>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction addSong(id){\n");
      out.write("\t\t\tXMLDataOperation(\"jukebox.jsp?com=addsong&id=\" + id, function(){\n");
      out.write("\t\t\t\tparent.reloadPlayData();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("\n");
}
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
